### ISSUE TITLE
Possibilidade de desabilitar a consulta

### ISSUE THREAD

**Issue by masakik** [uspdev/wsfoto#2]
Suponto que tenha uma aplicação que usa o wsfoto mas a instância da unidade não tem acesso ao serviço, poderia haver uma variável de ambiente WSFOTO_DISABLE=1 que permitiria usar a aplicação mesmo sem o serviço. 

É claro que a aplicação pode tatar isso mas facilitaria se estiver aqui.

**Comment by thiagogomesverissimo** [comment]
exemplo: https://github.com/uspdev/empresta/blob/master/.env.dist

Veja que 

```
# Credenciais do WSFOTO
USAR_WSFOTO=false
WSFOTO_USER=
WSFOTO_PASS=
```

Sim, poderia ser tratado aqui.

**Comment by masakik** [comment]
Vou fazer um pull request entao
